In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/Users/yaraemad/Desktop/Company_data.csv')

In [3]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [5]:
df.shape

(200, 4)

In [6]:
df.describe()

               TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [7]:
#Create x and y 
x = df['TV']
y = df['Sales']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
print(df.columns.tolist())

['TV', 'Radio', 'Newspaper', 'Sales']

In [10]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.7, test_size = 0.3, random_state = 100)

In [11]:
print (x_train)
print (y_train)

74     213.4
3      151.5
185    205.0
26     142.9
90     134.3
       ...
87     110.7
103    187.9
67     139.3
24      62.3
8        8.6
Name: TV, Length: 140, dtype: float64
74     17.0
3      16.5
185    22.6
26     15.0
90     14.0
       ...
87     16.0
103    19.7
67     13.4
24      9.7
8       4.8
Name: Sales, Length: 140, dtype: float64

In [12]:
import sklearn
import statsmodels.api as sm

In [13]:
import sklearn
import statsmodels.api as sm
x_train_sm=sm.add_constant(x_train)

In [14]:
Ir=sm.OLS(y_train, x_train).fit()
Ir.params

TV    0.08833
dtype: float64

In [15]:
Ir.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  Sales   R-squared (uncentered):                   0.924
Model:                            OLS   Adj. R-squared (uncentered):              0.924
Method:                 Least Squares   F-statistic:                              1702.
Date:                Wed, 12 Aug 2026   Prob (F-statistic):                    7.37e-80
Time:                        15:17:06   Log-Likelihood:                         -406.08
No. Observations:                 140   AIC:                                      814.2
Df Residuals:                     139   BIC:                                      817.1
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0883      0.002     41.253      0.000       0.084       0.093
==============================================================================
Omnibus:                        6.994   Durbin-Watson:                   1.773
Prob(Omnibus):                  0.030   Jarque-Bera (JB):                7.073
Skew:                          -0.515   Prob(JB):                       0.0291
Kurtosis:                       2.612   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""